version: '3.8'

services:
  piper-ai:
    build: .
    container_name: piper-ai
    ports:
      - "8071:8071"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xmx2g -Xms2g -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/app/logs/heap-dump.hprof
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8071/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./logs:/app/logs
    networks:
      - piper-network
    deploy:
      resources:
        limits:
          cpus: '1'
        reservations:
          cpus: '1'

networks:
  piper-network:
    driver: bridge 