server:
  port: 8071
spring:
  application:
    name: piper-ai
  datasource:
    url: jdbc:mysql://172.25.96.1:3306/piper_ai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

# ZooKeeper configuration
zookeeper:
  connect-string: 172.25.96.1:2181
  session-timeout-ms: 60000
  connection-timeout-ms: 15000
  base-path: /piper-ai
  node:
    ip: 172.25.96.1
    port: ${server.port}
    service-name: /piper-ai

# Worker configuration
worker:
  max-tasks: 10

# Logging configuration
logging:
  level:
    root: INFO
    com.zhuo.piper: INFO
    org.apache.zookeeper: WARN
    org.springframework: INFO
    org.apache.curator: WARN

load:
  balance:
    strategy: RoundRobin

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: cn.zhuo.infrastructure.persistence.po
  configuration:
    map-underscore-to-camel-case: true

dubbo:
  application:
    name: piper-ai
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://172.25.96.1:2181
    file: dubbo-registry-${server.port}.cache
  scan:
    base-packages: com.zhuo.piper.core.drive.zk,com.zhuo.piper.core.worker.impl
  provider:
    loadbalance: roundrobin
    weight: 0
  consumer:
    loadbalance: roundrobin